### ISSUE TITLE
Positive Likelihoods after Fit Minimimization.

### ISSUE THREAD

**Issue by karthik18495** [mashephe/AmpTools#106]
I have been trying to perform fits using AmpTools using the `group` build of `halld_sim`. The details of the Signal Events are below

## Signal MC Events

1. I am trying to generate `1p` state in Positive reflectivity `PosRefl`. 
2. It is generated in a narrow mass range `1.10 - 1.15 GeV`. and t range `0.15-0.30`
3. A total of 10k events are generated.

## Phasespace MC Events

1. 1M events are generated in the same range as signal events

## Fitting the generated signal

1. I fit the sample by initializing the production parameters to what was generated. This is for faster convergence.

When I fit, the fit converges with a positive `LogLikelihood`. Not sure what is going on.

The details of the software version are shown below

```bash
##################### Meta Info on software used ##############################
AMPTOOLS_HOME  /group/halld/Software/builds/Linux_CentOS7.7-x86_64-gcc4.8.5/amptools/AmpTools-0.14.4  ; AMPTOOLS_VERSION  0.14.4
HALLD_SIM_HOME  /group/halld/Software/builds/Linux_CentOS7.7-x86_64-gcc4.8.5/halld_sim/halld_sim-4.42.0  ; HALLD_SIM_VERSION  4.42.0
which fit : /group/halld/Software/builds/Linux_CentOS7.7-x86_64-gcc4.8.5/halld_sim/halld_sim-4.42.0/Linux_CentOS7.7-x86_64-gcc4.8.5/bin/fit
which omegapi_plotter : /group/halld/Software/builds/Linux_CentOS7.7-x86_64-gcc4.8.5/halld_sim/halld_sim-4.42.0/Linux_CentOS7.7-x86_64-gcc4.8.5/bin/omegapi_plotter
###############################################################################
```

The output log file is at `volatile/halld/home/ksuresh/ampToolsFits/neutralb1/ClassicTests/TestingAmpTools/EmulatedSignal/OutputEmulated.log`

To reproduce the problem in JLab's ifarm.

```bash
source /group/halld/Software/build_scripts/gluex_env_jlab.csh
```

Then, the source code is at 

```bash
/lustre19/expphy/volatile/halld/home/ksuresh/ampToolsFits/neutralb1/ClassicTests/TestingAmpTools/EmulatedSignal
```

Commands to run.

* `./runAll.csh` - will generate `Signal`, `PhaseSpace` and then performs `fit`
* `./runSignal.csh` and `./runPhaseSpace.csh` generate `Signal` and `PhaseSpace`
* `runFit.csh` to fit the generated `Signal` and `PhaseSpace` sample.

## Master branch of `AmpTools`

I confirmed that this issue still occurs with the master branch of `AmpTools`. 
To run with a Master version of `AmpTools`

```bash
source /work/halld/ksuresh/MY_HALLD_SIM_CPU2/setup_gluex.csh
```

and retry the `runFit.csh`.

**Comment by mashephe** [comment]
Karthik,

Is there a problem?  Your fit log looks normal.  

The value of -2 ln L is defined up to an arbitrary constant;  therefore you should not expect the sign to take a particular value.  

With version 0.14.4, which you are using, there were some changes to scaling of the likelihood so it may not be comparable with fits using previous versions.

The fit seems to converge... and the value of -2 ln L is less than what it was at initialization.  I don't see anything that looks obviously unhealthy.

Matt

**Comment by karthik18495** [comment]
Oh OK sorry for the false alarm. I tried to compare it with previous fits.
