### ISSUE TITLE
kMaxParticles = 7

### ISSUE THREAD

**Issue by jrstevenjlab** [mashephe/AmpTools#20]
In the new tag of 0.10.2 kMaxParticles was changed from 7 to 6.  Was there a reason to reduce this, or can it be switched back to 7 for the next tag?

**Comment by jrstevenjlab** [comment]
Checking on this again if a new release is upcoming soon.  Increasing the max particles to 7 would allow for beam, target and 5 body meson system.

**Comment by mashephe** [comment]
This has been merged with master.
