### ISSUE TITLE
hm12acc vs hm12gen

### ISSUE THREAD

**Issue by ch2ohch2oh** [mashephe/AmpTools#23]
Hello developer,

On page 11 of the doc (https://github.com/mashephe/AmpTools/blob/master/Tutorials/Dalitz/doc/doc.pdf), it says `hm12gen` is the acceptance corrected result. However, from the name, `hm12acc` seems to be the acceptance corrected result. Is that a typo or I misunderstood something?

Thanks,
Dazhi

**Comment by mashephe** [comment]
The documentation is correct.

hm12acc is filled with accepted MC weighted by the fit result.  Therefore it includes both the physics model and acceptance.

hm12gen is filled with generated MC weighted by the fit result.  It does not include the effects of acceptance.  In other words, if the acceptance was perfect, this is what one would expect the distributions to look like.

Hope this helps.

Matt

---------------------------------------------------------------------
Matthew Shepherd, Professor
Department of Physics, Indiana University, Swain West 265
727 East Third Street, Bloomington, IN 47405

Office Phone:  +1 812 856 5808

**Comment by ch2ohch2oh** [comment]
Thanks for the reply.

So AmpTool fits the real data with generated MC then applies the efficiency
correction afterwards? I thought the data was first re-weighted to get 100%
detector efficiency, then fitted with generated MC. Guess I was wrong.

Dazhi

**Comment by mashephe** [comment]
That's correct -- there is no rigorous way to correct the data.  AmpTools uses results of accepted MC to compute integrals of functions of the acceptance that are needed to construct a likelihood from the observed data.  You can think of this is matching the product of the acceptance and model-predicted intensity to the data.

Matt

---------------------------------------------------------------------
Matthew Shepherd, Professor
Department of Physics, Indiana University, Swain West 265
727 East Third Street, Bloomington, IN 47405

Office Phone:  +1 812 856 5808
