### ISSUE TITLE
Normalization for background with both positive and negative weights

### ISSUE THREAD

**Issue by aaust** [mashephe/AmpTools#25]
Mark Dalton reported issues with the normalization of the amplitudes when he uses signal and background files. Since he does accidental correction and sideband subtraction, both files contain events with positive and negative weights. There are a few pieces of the code which did not foresee this case:
- when the events of a background file are read in, all weights are forced to be negative
- to get the total number of events in the background sample, the absolute values of the weights are summed up
- the normalization term in the likelihood uses the total number of data events, disregarding the weights

I made a branch to fix this issue, but I am not allowed to push it to origin for review. Would it be OK to add my user name? Otherwise, I have to send the patch as a text file.

**Comment by mashephe** [comment]
Points 1 and 2 are related.. and this was a deliberate choice to avoid backwards compatibility.  At some point though, we are going to have to make this change.  Maybe now is good -- it was a choice whose limitations weren't fully understood at the time.  The last one should be correct if all backgrounds are really in the background file.  I think the true signal region events should always have a weight of 1.

**Comment by aaust** [comment]
Thanks, I submitted the pull request #26 .

In Mark's case, there are events that are both accidentals and in the mass sideband, which makes the product of the weights positive but smaller than one (e.g. 1/8). In a general, signal events can have weights different from 1 when weighting techniques (e.g. sPlot) are used. I introduced the sum of data weights for this case.

**Comment by mashephe** [comment]
This is addressed in AmpTools v0.11
